### ISSUE TITLE
Recommendations for "HyperCrate"

### ISSUE THREAD

**Issue by Annijang** [tererun/HyperCrate#1]
Thank you, I am a Chinese player, currently working on "zh_cn" file, I hope you can help me to improve this work.
I think it is also possible to add the probability of drawing the item to the work.
It is recommended to delete the selected text and keep the text on the left：
![QQ图片20220517130041](https://user-images.githubusercontent.com/75552974/168732745-502bc5a5-7764-4e31-a80d-9c290f2eb85e.png)
It is recommended to add language files in lang：
![1Q$@Z{3B3CGS7EG4`~V`GRR](https://user-images.githubusercontent.com/75552974/168733665-9f888ead-cf96-414c-b0b5-f1e032fdb939.png)
It is recommended to add language files in lang, the white text on the right:
![QQ图片20220517132135](https://user-images.githubusercontent.com/75552974/168734955-617ecb74-73c4-41cb-9e18-f93a9fbc3078.png)

**Comment by tererun** [comment]
Thank you for using this plugin!

The title suffix of preview can't delete because it's used to detect the HyperCrate GUI.
However, I can fix this by using other methods, so please wait for the update!

Other unsupported words will also be supported.

**Comment by tererun** [comment]
@Annijang 

We have applied the feedback we received here in Patch-1.1.3.
We hope you will use the latest version and enjoy the new features!
